# Generated by Django 2.0.13 on 2021-06-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Info',
            fields=[
                ('pid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('category_L', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'item_info',
                'managed': False,
            },
        ),
    ]
